apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-deployment-3
  name: nginx-deployment-3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-deployment-3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-deployment-3
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
