apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: giropopops
  name: giropopops2
spec:
  containers:
  - image: nginx
    name: giropopops
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
